// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backEnd_EM.Models;

#nullable disable

namespace backEnd_EM.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240416161658_ManyToMany")]
    partial class ManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backEnd_EM.Models.Analytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountOfTimesLogin")
                        .HasColumnType("integer");

                    b.Property<int?>("AthletesId")
                        .HasColumnType("integer");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RecentLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AthletesId");

                    b.ToTable("Analytics");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.Analyse", b =>
                {
                    b.Property<int>("AnalyseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnalyseId"));

                    b.Property<int?>("AthletesId")
                        .HasColumnType("integer");

                    b.Property<string>("BreakDown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("videoURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnalyseId");

                    b.HasIndex("AthletesId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.Appointments", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<int?>("AthletesId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Time")
                        .HasColumnType("real");

                    b.Property<string>("TypeApointment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AthletesId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.Athletes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Guardian")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ResetTokenExperies")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.Guardians", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AthletesId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Guardians");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.ProgramAthlete", b =>
                {
                    b.Property<int>("ProgramsId")
                        .HasColumnType("integer");

                    b.Property<int?>("AthletesId")
                        .HasColumnType("integer");

                    b.HasKey("ProgramsId", "AthletesId");

                    b.HasIndex("AthletesId");

                    b.ToTable("programAthletes");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.Programs", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgramId"));

                    b.Property<DateOnly>("PurchasedDate")
                        .HasColumnType("date");

                    b.HasKey("ProgramId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.ProgressTracker", b =>
                {
                    b.Property<int>("ProgressTrackerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgressTrackerId"));

                    b.Property<int?>("AthletesId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<float>("Value_Dor_Date")
                        .HasColumnType("real");

                    b.Property<string>("WorkOut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProgressTrackerId");

                    b.HasIndex("AthletesId");

                    b.ToTable("ProgressTrackers");
                });

            modelBuilder.Entity("backEnd_EM.Models.Analytics", b =>
                {
                    b.HasOne("backEnd_EM.Properties.Models.Athletes", null)
                        .WithMany("Analytics")
                        .HasForeignKey("AthletesId");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.Analyse", b =>
                {
                    b.HasOne("backEnd_EM.Properties.Models.Athletes", null)
                        .WithMany("Analyses")
                        .HasForeignKey("AthletesId");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.Appointments", b =>
                {
                    b.HasOne("backEnd_EM.Properties.Models.Athletes", null)
                        .WithMany("Appointments")
                        .HasForeignKey("AthletesId");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.ProgramAthlete", b =>
                {
                    b.HasOne("backEnd_EM.Properties.Models.Athletes", "Athlete")
                        .WithMany("ProgramAthletes")
                        .HasForeignKey("AthletesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backEnd_EM.Properties.Models.Programs", "Program")
                        .WithMany("ProgramAthletes")
                        .HasForeignKey("ProgramsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.ProgressTracker", b =>
                {
                    b.HasOne("backEnd_EM.Properties.Models.Athletes", null)
                        .WithMany("ProgressTrackers")
                        .HasForeignKey("AthletesId");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.Athletes", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Analytics");

                    b.Navigation("Appointments");

                    b.Navigation("ProgramAthletes");

                    b.Navigation("ProgressTrackers");
                });

            modelBuilder.Entity("backEnd_EM.Properties.Models.Programs", b =>
                {
                    b.Navigation("ProgramAthletes");
                });
#pragma warning restore 612, 618
        }
    }
}
